# Generated by Django 5.2.12 on 2026-03-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='leitor',
            options={'verbose_name': 'Leitor', 'verbose_name_plural': 'Leitores'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='data_plub',
            new_name='data_publicacao',
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status do livro'),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(verbose_name='Data do empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Data da devolução')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Devolvido')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leitor', verbose_name='Leitor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
